config/routes.rb
Todo::Application.routes.draw do
  resources :projects do
    resources :tasks
  end

  root :to => "projects#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name
  has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :name, :project_id
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find params[:id]
    @tasks = @project.tasks
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @project = Project.find params[:project_id]
    @task = Task.new
  end

  def create
    @project = Project.find params[:project_id]
    @task = @project.tasks.build params[:task]

    if @task.save
      redirect_to project_url(@project)
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_name(project)
    "#{project.name} (#{project.tasks.count})"
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_project.html.erb
<p>
  <%= link_to project_name(project), project %>
</p>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<h2>Projekty</h2>

<%= render @projects %>

app/views/projects/new.html.erb
<h1>Projects#new</h1>
<p>Find me in app/views/projects/new.html.erb</p>

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>

<p>
  <%= link_to "&laquo; Spat".html_safe, projects_path %>

  <%= link_to "Novy task", new_project_task_path(@project) %>
</p>

<%= render @tasks %>

app/views/tasks/_task.html.erb
<p><%= task.name %></p>

app/views/tasks/new.html.erb
<%= form_for [@project, @task] do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>